apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default
spec:
  # AMI configuration - use latest AL2023 EKS-optimized AMI
  amiSelectorTerms:
  - alias: al2023@latest
  
  # Instance family configuration
  instanceStorePolicy: "RAID0"  # Use instance store if available
  
  # Subnet configuration - use the private subnets with Karpenter discovery tags
  subnetSelectorTerms:
  - tags:
      karpenter.sh/discovery: "n0sebleed-eks"
  
  # Security group configuration - use cluster security group
  securityGroupSelectorTerms:
  - tags:
      kubernetes.io/cluster/n0sebleed-eks: "owned"
  
  # Instance profile for nodes
  role: "KarpenterNodeRole-n0sebleed-eks"
  
  # User data to bootstrap nodes
  userData: |
    #!/bin/bash
    /etc/eks/bootstrap.sh n0sebleed-eks
    
  # Instance metadata service configuration
  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 2
    httpTokens: required
  
  # Tags applied to all provisioned instances
  tags:
    Name: "Karpenter-n0sebleed-eks"
    Environment: "test"
    ManagedBy: "Karpenter"
---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: default
spec:
  # Template for nodes that Karpenter will provision
  template:    
    spec:
      # Node class reference
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: default
      
      # Instance requirements
      requirements:
      - key: kubernetes.io/arch
        operator: In
        values: ["amd64"]
      - key: kubernetes.io/os  
        operator: In
        values: ["linux"]
      - key: karpenter.sh/capacity-type
        operator: In
        values: ["on-demand", "spot"]  # Allow both on-demand and spot
      - key: node.kubernetes.io/instance-type
        operator: In
        values: 
        - t3.micro
        - t3.small
      
      # Node properties
      taints: []  # No taints for general workloads
      startupTaints: []
  
  # Scaling and lifecycle configuration
  limits:
    cpu: 20      # Max 20 CPU cores across all nodes in this pool
    memory: 40Gi # Max 40GB memory across all nodes in this pool

  # Disruption settings
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized    # Consolidate nodes when empty
    consolidateAfter: 30s            # Wait 30s before consolidating