apiVersion: apps/v1
kind: Deployment
metadata:
  name: workload-a
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-a
  template:
    metadata:
      labels:
        app: workload-a
    spec:
      # Toleration to allow scheduling on workload-a tainted nodes
      tolerations:
      - key: workload
        value: workload-a
        effect: NoSchedule
        operator: Equal
      
      # Node affinity to prefer workload-a nodes
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: workload
                operator: In
                values: ["workload-a"]
      
      containers:
      - name: nginx
        image: nginx:1.21
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: workload-a-service
  namespace: default
spec:
  selector:
    app: workload-a
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  type: ClusterIP